name: docs
on:
  push:
    branches:
    - docs

permissions:
  id-token: write
  pages: write

jobs:
  docs:
    #environment:
    #  name: github-pages
    #  url: ${{steps.deployment.outputs.page_url}}
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          pip3 install sphinx-rtd-theme
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/